// <auto-generated />
using System;
using Data.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(AplicationContext))]
    [Migration("20210216141622_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Adress = "Slavonski Brod, Branimirova 86",
                            DateOfBirth = new DateTime(1995, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lkristic@eko.hr",
                            IsAdmin = true,
                            Name = "Lukas",
                            Password = "Kong35",
                            Surname = "Krištić"
                        },
                        new
                        {
                            Id = 2L,
                            Adress = "Slavonski Brod, Branimirova 86",
                            DateOfBirth = new DateTime(1963, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mato@eko.hr",
                            IsAdmin = true,
                            Name = "Mato",
                            Password = "Baki49",
                            Surname = "Krištić"
                        },
                        new
                        {
                            Id = 3L,
                            Adress = "Osijek, Stjepana Radića 2",
                            DateOfBirth = new DateTime(1991, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tmintra@eko.hr",
                            IsAdmin = false,
                            Name = "Tony",
                            Password = "Legolas4",
                            Surname = "Mitrandil"
                        },
                        new
                        {
                            Id = 4L,
                            Adress = "Rijeka, Ivana Držića 7",
                            DateOfBirth = new DateTime(1993, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "aolimp@eko.hr",
                            IsAdmin = false,
                            Name = "Artemida",
                            Password = "Hades191",
                            Surname = "Olimp"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
